spring:
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://192.168.100.77:3306/ituac_uac?characterEncoding=utf8&useSSL=false




security:
  oauth2:
    client:
      clientId: ituac-browser
      clientSecret: ituacClientSecret
      access-token-uri: http://localhost:7979/uac/oauth/token
      user-authorization-uri: http://localhost:7979/uac/oauth/authorize
    resource:
      id: browser-service
      user-info-uri: http://localhost:7979/uac/user
      
ituac:
  oauth2:
    client:
      id: ${security.oauth2.resource.id}
      accessTokenUrl: http://localhost:7979/uac/oauth/token
      clientId: ${security.oauth2.client.clientId}
      clientSecret: ${security.oauth2.client.clientSecret}
      clientAuthenticationScheme: header

oauth2:
      tokenStore: jwt
      clients[0]:
        clientId: ituac-client-uac
        clientSecret: ituacClientSecret
        accessTokenValidateSeconds: 7200
        scope: "*"
      clients[1]:
        clientId: ituac-client-gateway
        clientSecret: ituacClientSecret
        accessTokenValidateSeconds: 7200
        scope: "*"
