spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      enabled: true
      max-request-size: 50MB
      max-file-size: 50MB  
 
security:
  oauth2:
    client:
      clientId: ituac-client-gateway
      clientSecret: ituacClientSecret
      access-token-uri:  
      user-authorization-uri: 
    resource:
      user-info-uri: http://ituac-gateway:7979/uac/user
      prefer-token-info: false
      jwt:
        key-uri: 


zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  forceOriginalQueryStringEncoding: true
