spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      enabled: true
      max-request-size: 50MB
      max-file-size: 50MB

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  forceOriginalQueryStringEncoding: true
  routes:
    uac-route:    #认证服务
      # 响应路径
      path: /uac/**
      # 敏感头信息
      sensitiveHeaders:
#      strip-prefix: false
      # 重定向到的服务，根据服务Id昵称从注册中心访问服务地址
      service-id: ituac-service-uac
      ribbon:
        eager-load:
          enabled: true
        MaxAutoRetries: 1
        MaxAutoRetriesNextServer: 2
        OkToRetryOnAllOperations: false
        ConnectTimeout: 10000
        ReadTimeout: 10000
  #添加代理头
  add-proxy-headers: true
        
        
#安全配置
security:
  oauth2:
    resource:
      user-info-uri: http://127.0.0.1:7979/uac/user
      prefer-token-info: false

ituacc:
  enableSqlLogInterceptor: false
