spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      enabled: true
      max-request-size: 50MB
      max-file-size: 50MB

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  forceOriginalQueryStringEncoding: true
  routes:
    uac-route:
      path: /uac/**
      sensitiveHeaders:
#      strip-prefix: false
      service-id: ituac-service-uac
      ribbon:
        eager-load:
          enabled: true
        MaxAutoRetries: 1
        MaxAutoRetriesNextServer: 2
        OkToRetryOnAllOperations: false
        ConnectTimeout: 10000
        ReadTimeout: 10000
        
        
security:
  oauth2:
    client:
      clientId: ituac-client-gateway
      clientSecret: ituacCloudClientSecret
      access-token-uri: http://ituaccloud-gateway:7979/uac/oauth/token
      user-authorization-uri: http://ituaccloud-gateway:7979/uac/oauth/authorize
    resource:
      user-info-uri: http://ituaccloud-gateway:7979/uac/user
      prefer-token-info: false
      jwt:
        key-uri: http://ituac-service-uac:8000/oauth/token

proxy:
  auth:
    routes:
      uac-route: oauth2
      mdc-route: oauth2

paascloud:
  enableSqlLogInterceptor: false
